"use client";
import { ImageOff } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";

export default function AssetsPage() {
  return (
    <div className="space-y-4">
      <h2 className="text-lg font-semibold">Assets</h2>
      <Card>
        <CardContent className="flex flex-col items-center justify-center py-16 text-center gap-3">
          <ImageOff className="h-10 w-10 text-muted-foreground" />
          <div>
            <p className="text-sm font-medium">Asset library coming soon</p>
            <p className="text-xs text-muted-foreground mt-1">
              Visual assets generated by the AI workflow will appear here once the assets API is wired up.
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
